apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack:latest
          ports:
            - containerPort: 6379
            - containerPort: 8001
          env:
            - name: REDIS_ARGS
              value: "--appendonly yes"

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
    - name: redis-insight
      port: 8001
      targetPort: 8001
      protocol: TCP
  type: LoadBalancer
  externalTrafficPolicy: Local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: meetandmore-backend:local
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongo-uri
            - name: PORT
              value: "5000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: NODE_ENV
              value: "production"
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rapidapi-key
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cloudinary-cloud-name
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cloudinary-api-key
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: cloudinary-api-secret
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: CLIENT_ORIGIN
              value: "http://localhost:5173"
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: twilio-account-sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: twilio-auth-token
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: twilio-phone-number
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-region
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: s3-bucket-name
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: aws-secret-access-key
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email-user
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: email-pass
            - name: LINKEDIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: linkedin-client-id
            - name: LINKEDIN_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: linkedin-client-secret
            - name: LINKEDIN_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: linkedin-redirect-uri
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: razorpay-key-id
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: razorpay-key-secret
            - name: RAZORPAY_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: razorpay-webhook-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  #Env removed
