const mongoose = require("mongoose");
const { v4: uuidv4 } = require("uuid");

const RewardSchema = new mongoose.Schema(
  {
    _id: { type: String, default: uuidv4 },
    referralType: {
      type: String,
      enum: ["standard", "influencer", "special", "first-time", "no-show"],
      required: true,
    },
    INR: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    USD: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    CAD: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    GBP: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    EUR: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    AUD: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    SGD: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    HKD: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    JPY: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    KRW: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    MYR: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    THB: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    AED: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    QAR: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    SAR: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    EGP: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    ZAR: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    ARS: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    MXN: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    NGN: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    RUB: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    TRY: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    CLP: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    BRL: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    PEN: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    COP: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    RWF: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    KES: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    BDT: {
      userReward: { type: Number, default: 0 },
      ownerReward: { type: Number, default: 0 },
    },
    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

// Initialize default rewards
RewardSchema.statics.initializeDefaultRewards = async function () {
  const defaultRewards = [
    {
      referralType: "standard",
      INR: { userReward: 150, ownerReward: 1000 },
      USD: { userReward: 6, ownerReward: 40 },
      CAD: { userReward: 5, ownerReward: 30 },
      GBP: { userReward: 3, ownerReward: 28 },
      EUR: { userReward: 3, ownerReward: 32 },
      AUD: { userReward: 3, ownerReward: 30 },
      SGD: { userReward: 6, ownerReward: 60 },
      HKD: { userReward: 20, ownerReward: 200 },
      JPY: { userReward: 150, ownerReward: 2800 },
      KRW: { userReward: 1500, ownerReward: 24000 },
      MYR: { userReward: 7, ownerReward: 60 },
      THB: { userReward: 80, ownerReward: 800 },
      AED: { userReward: 10, ownerReward: 100 },
      QAR: { userReward: 7, ownerReward: 80 },
      SAR: { userReward: 8, ownerReward: 80 },
      EGP: { userReward: 50, ownerReward: 600 },
      ZAR: { userReward: 50, ownerReward: 460 },
      ARS: { userReward: 150, ownerReward: 2400 },
      MXN: { userReward: 30, ownerReward: 400 },
      NGN: { userReward: 300, ownerReward: 6000 },
      RUB: { userReward: 150, ownerReward: 2000 },
      TRY: { userReward: 25, ownerReward: 300 },
      CLP: { userReward: 500, ownerReward: 14000 },
      BRL: { userReward: 5, ownerReward: 70 },
      PEN: { userReward: 4, ownerReward: 60 },
      COP: { userReward: 3000, ownerReward: 60000 },
      RWF: { userReward: 700, ownerReward: 14000 },
      KES: { userReward: 60, ownerReward: 2000 },
      BDT: { userReward: 60, ownerReward: 1600 },
    },
    {
      referralType: "influencer",
      INR: { userReward: 100, ownerReward: 0 },
      USD: { userReward: 4, ownerReward: 0 },
      CAD: { userReward: 3, ownerReward: 0 },
      GBP: { userReward: 2, ownerReward: 0 },
      EUR: { userReward: 2, ownerReward: 0 },
      AUD: { userReward: 3, ownerReward: 0 },
      SGD: { userReward: 6, ownerReward: 0 },
      HKD: { userReward: 20, ownerReward: 0 },
      JPY: { userReward: 150, ownerReward: 0 },
      KRW: { userReward: 1500, ownerReward: 0 },
      MYR: { userReward: 7, ownerReward: 0 },
      THB: { userReward: 80, ownerReward: 0 },
      AED: { userReward: 10, ownerReward: 0 },
      QAR: { userReward: 7, ownerReward: 0 },
      SAR: { userReward: 8, ownerReward: 0 },
      EGP: { userReward: 50, ownerReward: 0 },
      ZAR: { userReward: 50, ownerReward: 0 },
      ARS: { userReward: 150, ownerReward: 0 },
      MXN: { userReward: 30, ownerReward: 0 },
      NGN: { userReward: 300, ownerReward: 0 },
      RUB: { userReward: 150, ownerReward: 0 },
      TRY: { userReward: 25, ownerReward: 0 },
      CLP: { userReward: 500, ownerReward: 0 },
      BRL: { userReward: 5, ownerReward: 0 },
      PEN: { userReward: 4, ownerReward: 0 },
      COP: { userReward: 3000, ownerReward: 0 },
      RWF: { userReward: 700, ownerReward: 0 },
      KES: { userReward: 60, ownerReward: 0 },
      BDT: { userReward: 60, ownerReward: 0 },
    },
    {
      referralType: "special",
      INR: { userReward: 200, ownerReward: 0 },
      USD: { userReward: 6, ownerReward: 0 },
      CAD: { userReward: 5, ownerReward: 0 },
      GBP: { userReward: 3, ownerReward: 0 },
      EUR: { userReward: 3, ownerReward: 0 },
      AUD: { userReward: 3, ownerReward: 0 },
      SGD: { userReward: 6, ownerReward: 0 },
      HKD: { userReward: 20, ownerReward: 0 },
      JPY: { userReward: 150, ownerReward: 0 },
      KRW: { userReward: 1500, ownerReward: 0 },
      MYR: { userReward: 7, ownerReward: 0 },
      THB: { userReward: 80, ownerReward: 0 },
      AED: { userReward: 10, ownerReward: 0 },
      QAR: { userReward: 7, ownerReward: 0 },
      SAR: { userReward: 8, ownerReward: 0 },
      EGP: { userReward: 50, ownerReward: 0 },
      ZAR: { userReward: 50, ownerReward: 0 },
      ARS: { userReward: 150, ownerReward: 0 },
      MXN: { userReward: 30, ownerReward: 0 },
      NGN: { userReward: 300, ownerReward: 0 },
      RUB: { userReward: 150, ownerReward: 0 },
      TRY: { userReward: 25, ownerReward: 0 },
      CLP: { userReward: 500, ownerReward: 0 },
      BRL: { userReward: 5, ownerReward: 0 },
      PEN: { userReward: 4, ownerReward: 0 },
      COP: { userReward: 3000, ownerReward: 0 },
      RWF: { userReward: 700, ownerReward: 0 },
      KES: { userReward: 60, ownerReward: 0 },
      BDT: { userReward: 60, ownerReward: 0 },
    },
    {
      referralType: "first-time",
      INR: { userReward: 100, ownerReward: 0 },
      USD: { userReward: 4, ownerReward: 0 },
      CAD: { userReward: 3, ownerReward: 0 },
      GBP: { userReward: 4, ownerReward: 0 },
      EUR: { userReward: 4, ownerReward: 0 },
      AUD: { userReward: 3, ownerReward: 0 },
      SGD: { userReward: 6, ownerReward: 0 },
      HKD: { userReward: 20, ownerReward: 0 },
      JPY: { userReward: 150, ownerReward: 0 },
      KRW: { userReward: 1500, ownerReward: 0 },
      MYR: { userReward: 7, ownerReward: 0 },
      THB: { userReward: 80, ownerReward: 0 },
      AED: { userReward: 10, ownerReward: 0 },
      QAR: { userReward: 7, ownerReward: 0 },
      SAR: { userReward: 8, ownerReward: 0 },
      EGP: { userReward: 50, ownerReward: 0 },
      ZAR: { userReward: 50, ownerReward: 0 },
      ARS: { userReward: 150, ownerReward: 0 },
      MXN: { userReward: 30, ownerReward: 0 },
      NGN: { userReward: 300, ownerReward: 0 },
      RUB: { userReward: 150, ownerReward: 0 },
      TRY: { userReward: 25, ownerReward: 0 },
      CLP: { userReward: 500, ownerReward: 0 },
      BRL: { userReward: 5, ownerReward: 0 },
      PEN: { userReward: 4, ownerReward: 0 },
      COP: { userReward: 3000, ownerReward: 0 },
      RWF: { userReward: 700, ownerReward: 0 },
      KES: { userReward: 60, ownerReward: 0 },
      BDT: { userReward: 60, ownerReward: 0 },
    },
    {
      referralType: "no-show",
      INR: { userReward: 700, ownerReward: 0 },
      USD: { userReward: 23, ownerReward: 0 },
      CAD: { userReward: 19, ownerReward: 0 },
      GBP: { userReward: 18, ownerReward: 0 },
      EUR: { userReward: 20, ownerReward: 0 },
      AUD: { userReward: 18, ownerReward: 0 },
      SGD: { userReward: 35, ownerReward: 0 },
      HKD: { userReward: 120, ownerReward: 0 },
      JPY: { userReward: 1500, ownerReward: 0 },
      KRW: { userReward: 14000, ownerReward: 0 },
      MYR: { userReward: 34, ownerReward: 0 },
      THB: { userReward: 420, ownerReward: 0 },
      AED: { userReward: 53, ownerReward: 0 },
      QAR: { userReward: 44, ownerReward: 0 },
      SAR: { userReward: 45, ownerReward: 0 },
      EGP: { userReward: 320, ownerReward: 0 },
      ZAR: { userReward: 250, ownerReward: 0 },
      ARS: { userReward: 1400, ownerReward: 0 },
      MXN: { userReward: 250, ownerReward: 0 },
      NGN: { userReward: 3300, ownerReward: 0 },
      RUB: { userReward: 1200, ownerReward: 0 },
      TRY: { userReward: 170, ownerReward: 0 },
      CLP: { userReward: 7300, ownerReward: 0 },
      BRL: { userReward: 38, ownerReward: 0 },
      PEN: { userReward: 35, ownerReward: 0 },
      COP: { userReward: 33000, ownerReward: 0 },
      RWF: { userReward: 7400, ownerReward: 0 },
      KES: { userReward: 1200, ownerReward: 0 },
      BDT: { userReward: 880, ownerReward: 0 },
    },
  ];

  for (const reward of defaultRewards) {
    await this.findOneAndUpdate({ referralType: reward.referralType }, reward, {
      upsert: true,
      new: true,
    });
  }
};

module.exports = mongoose.model("Reward", RewardSchema);
